#Expyriment 0.9.0 (Python 2.7.15), .xpe-file, coding: cp1252
#date: Wed Jan 30 2019 15:45:57
#sha1: 195d6c
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: ('Windows', 'EDU-JBOOTH-MOB', '10', '10.0.17134', 'AMD64', 'Intel64 Family 6 Model 142 Stepping 9, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
11052,design,log,
#design: #exp: whole_number_to_position
#design: block_cnt,block_id,trial_cnt,trial_id
11053,design,logged,
11053,Experiment,started
11066,Stimulus,presented,1
11074,Stimulus,presented,1
11096,Stimulus,presented,1
11113,Stimulus,presented,2
11607,TextInput,entered,
11618,Stimulus,presented,2
11625,Stimulus,presented,2
11646,Stimulus,presented,2
11658,Stimulus,presented,3
12089,TextInput,entered,
12090,Invalid subject ID ()
12090,stdout,received,'15:01:09.946: Invalid subject ID ()'
12101,Stimulus,presented,3
12112,Stimulus,presented,3
12135,Stimulus,presented,3
12145,Stimulus,presented,4
12736,Stimulus,presented,4
13292,Stimulus,presented,4
13931,TextInput,entered,jj
13934,stderr,received,'Traceback (most recent call last):'
13935,stderr,received,'  File "C:\\Users\\stemlab\\Documents\\GitHub\\tft\\whole_number_to_position.py", line 72, in <module>'
13937,stderr,received,'    num2pos.create_experiment_objects(exp_info)'
13937,stderr,received,'  File "C:\\Python27\\lib\\site-packages\\trajtrackerp\\num2pos\\_n2p_init.py", line 53, in create_experiment_objects'
13939,stderr,received,'    load_data_source(exp_info)'
13939,stderr,received,'  File "C:\\Python27\\lib\\site-packages\\trajtrackerp\\num2pos\\_n2p_init.py", line 245, in load_data_source'
13940,stderr,received,'    exp_info.trials, fieldnames = loader.load_file(ds)'
13940,stderr,received,'  File "C:\\Python27\\lib\\site-packages\\trajtracker\\io\\_CSVLoader.py", line 96, in load_file'
13941,stderr,received,'    row = self._transform_types(row, filename)'
13941,stderr,received,'  File "C:\\Python27\\lib\\site-packages\\trajtracker\\io\\_CSVLoader.py", line 157, in _transform_types'
13942,stderr,received,'    format(row[self.FLD_LINE_NUM], filename, e))'
13944,stderr,received,"trajtracker.BadFormatError: BadFormatError: Invalid CSV file format (line 47 in whole_number_to_position_2019.csv): invalid literal for int() with base 10: ''"
